### ISSUE TITLE
换肤方案

### ISSUE THREAD

**Issue by xxholly32** [xxholly32/vite-components-playground#3]
利用vite的功能实现

+ [ ] 动态修改文件可以实时改变组件库的皮肤
    默认已经支持修改 tailwind.config.js 可以动态改变皮肤颜色，如何实现在网页端实现换肤，尝试使用 网页修改皮肤的色值去修改，将tailwind.config.js，放置与网页端，并做到实时修改

**Comment by xxholly32** [comment]
暂时无法实现

**Comment by i7eo** [comment]
> 暂时无法实现
动态修改 css 变量应该可以实现

**Comment by xxholly32** [comment]
已经有实现方案可以参考：https://github.com/xxholly32/vite-theme-test
