### ISSUE TITLE
使用 yarn build构建，项目没有把tailwind 打包进去

### ISSUE THREAD

**Issue by shlroland** [xxholly32/vite-components-playground#4]

**Comment by xxholly32** [comment]
嗯最近项目还在用lerna重构，尽快支持

**Comment by shlroland** [comment]
我也写了个 vue3的组件库 参照你的配置来写文档，一开始就上了lerna，也出现了无法把tailwind打包进去的情况，不知道这是什么原因导致的？[rol-ui](https://github.com/shlroland/rol-ui-vue3)

**Comment by shlroland** [comment]
> 我也写了个 vue3的组件库 参照你的配置来写文档，一开始就上了lerna，也出现了无法把tailwind打包进去的情况，不知道这是什么原因导致的？

[](https://github.com/shlroland/rol-ui-vue3)

**Comment by xxholly32** [comment]
额我试了下你的build是好的，`main.ts`中的改成

```
// import '../packages/style/index.scss'
import '../lib/style/css/index.css'
```

还是说你想把tailwindcss打到你的lib里面？

还是说你想用vite build的时候没有打进去，不过我也没看到你有 vite build的指令

**Comment by shlroland** [comment]
> 额我试了下你的build是好的，`main.ts`中的改成
> 
> ```
> // import '../packages/style/index.scss'
> import '../lib/style/css/index.css'
> ```
> 
> 还是说你想把tailwindcss打到你的lib里面？
> 
> 还是说你想用vite build的时候没有打进去，不过我也没看到你有 vite build的指令

tailwindcss 我只想用vite build 打进文档的dist包中，但是每次执行完vite build后，tailwindcss 是不在dist/assets/style.css里面，导致整个文档的布局css 丢失了

**Comment by xxholly32** [comment]
> tailwindcss 我只想用vite build 打进文档的dist包中，但是每次执行完vite build后，tailwindcss 是不在dist/assets/style.css里面，导致整个文档的布局css 丢失了

嗯确实有这个问题，我现在的项目也类似的问题，我看下

**Comment by xxholly32** [comment]
你的这个代码配置有问题 https://github.com/shlroland/rol-ui-vue3/blob/master/tailwind.config.js#L6

不是 src 应该是 docs ，我已经跑过没什么问题。
