### ISSUE TITLE
如何使用 lerna 创建 src 目录

### ISSUE THREAD

**Issue by i7eo** [xxholly32/vite-components-playground#5]
这个项目很棒，我正在努力学习。
想问下楼主 通过 `lerna create xxx` 来创建 带有src目录的文件呢？
我创建出来的只有 lib ，但是我看你是有src。是手动改的还是通过一些参数控制？

**Comment by i7eo** [comment]
目前看来只能自己手动创建了

**Comment by xxholly32** [comment]
这个项目现在还是vite1版本的，后面会改成vite2 

你的问题是lerna的问题，建议先学习一下lerna的原理
